turtlebot3: #namespace
    linear_forward_speed: 0.5 # Speed for going forwards
    linear_turn_speed: 0.05 # Linear speed when turning
    angular_speed: 0.3 # Angular speed when turning Left or Right

    scan_ranges: 360 #73 #  Number of scans to use, e.g 37 means 36 scans because the last scan is the same as the first scan
    max_scan_range: 0.6
    min_scan_range: 0.0850 #0.0850 #0.0802 #0.136

    desired_pose:
      x: 1.6
      y: 0.0
      z: 0.0

    starting_pose:
      x: 0.0
      y: 0.0
      z: 0.0
